---
title: 'Tidy Tuesday #3'
author: "RACHEL PERCY"
output: 
  html_document:
    df_print: paged
    code_download: true
    theme: cerulean
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, error=TRUE, message=FALSE, warning=FALSE)
```

```{r libraries}
library(tidyverse)     # for graphing and data cleaning
library(lubridate)     # for date manipulation
library(ggthemes)      # for even more plotting themes
library(openintro)
theme_set(theme_minimal()) # My favorite ggplot() theme :)
```

## Data choice 2: Alternative fuel stations

```{r}

# Read in the data

stations <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-03-01/stations.csv')

```

Read more about the Alternative fuel stations data, including definitions of variables, [here](https://github.com/rfordatascience/tidytuesday/blob/master/data/2022/2022-03-01/readme.md). 



```{r, fig.alt= "Choropleth Map of United States Showing Number of Alternative Charging Stations in Each State California has the most"}
states_map <- map_data("state")

stations %>% 
  filter(CITY != "Ontario") %>% 
  rename(region = STATE) %>% 
  group_by(region) %>% 
  summarise(state_n = n()) %>% 
  mutate(state_name = str_to_lower(abbr2state(`region`))) %>% 
  ggplot() +
  geom_map(map = states_map,
           aes(map_id = state_name,
               fill = state_n)) +
  scale_fill_viridis_c(option = "viridis") +
  expand_limits(x = states_map$long, y = states_map$lat) +
  theme_map() +
  labs(title = "Number of Alternative Charging Stations in Each State",
       fill = "Number of Stations",
       caption = "Designed by Rachel Percy | March 8, 2022 \n Data from U.S. Department of Energy") +
  theme(legend.background = element_blank())
  

```


